submitit ERROR (2024-01-04 20:01:53,261) - Submitted job triggered an exception
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/mohammed/seg/lib/python3.8/site-packages/submitit/core/_submit.py", line 11, in <module>
    submitit_main()
  File "/home/mohammed/seg/lib/python3.8/site-packages/submitit/core/submission.py", line 76, in submitit_main
    process_job(args.folder)
  File "/home/mohammed/seg/lib/python3.8/site-packages/submitit/core/submission.py", line 69, in process_job
    raise error
  File "/home/mohammed/seg/lib/python3.8/site-packages/submitit/core/submission.py", line 55, in process_job
    result = delayed.result()
  File "/home/mohammed/seg/lib/python3.8/site-packages/submitit/core/utils.py", line 133, in result
    self._result = self.function(*self.args, **self.kwargs)
  File "run_with_submitit_finetune.py", line 64, in __call__
    run_class_finetuning.main(self.args, self.parser)
  File "/mnt/c/Users/Moham/Desktop/Harmony/unilm/beit/run_class_finetuning.py", line 224, in main
    utils.init_distributed_mode(args)
  File "/mnt/c/Users/Moham/Desktop/Harmony/unilm/beit/utils.py", line 293, in init_distributed_mode
    torch.distributed.init_process_group(backend=args.dist_backend, init_method=args.dist_url,
  File "/home/mohammed/seg/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 455, in init_process_group
    barrier()
  File "/home/mohammed/seg/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 1960, in barrier
    work = _default_pg.barrier()
RuntimeError: NCCL error in: /pytorch/torch/lib/c10d/ProcessGroupNCCL.cpp:784, unhandled system error, NCCL version 2.7.8
